config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "screens#index"
  resources :screens do
    resources :descriptions, only: :create
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/screen.rb
class Screen < ApplicationRecord
  mount_uploader :picture, PictureUploader
  validates :description, presence: true
  validates :picture, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :screens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def new
      @screen = Screen.new
    end

	def index
	  @screens = Screen.all	
	end

	def create
	  @screen = current_user.screens.create(screen_params)
	  if @screen.valid?
	    redirect_to root_path
	  else
	    render :new, status: :unprocessable_entity
	  end
	end



  private

  def screen_params
    params.require(:screen).permit(:description, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homescreen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      You're signed in as <%= current_user.email %>.
      
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

      <%= link_to "CLICK HERE TO ADD YOUR SCREENSHOT!", new_screen_path %>
      
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    


  </body>
</html>

app/views/screens/index.html.erb
<h1>Screens!</h1>

<% @screens.each do |screen| %>
<div>
  <%= screen.description %>
  <%= image_tag screen.picture.to_s %>
</div>
<% end %>

app/views/screens/new.html.erb
<h1>New Screen</h1>

<%= simple_form_for @screen do |f| %>
  <%= f.input :picture %>
  <%= f.input :description %>
  <%= f.submit "Submit" %>
<% end %>